with_variants_array! {
#[derive(Debug)]
#[derive(Clone, Copy)]
#[derive(Eq, PartialEq, Hash)]
#[derive(Ord, PartialOrd)]
pub enum Suit {
    Spades,
    Hearts,
    Diamonds,
    Clubs
}}


impl Suit {
    inverted_match_constructor! {
        pub fn from_char(char) -> Self { /* generated by inverted_match_constructor */ }
        pub fn to_char(self) -> char {
            match self {
                Suit::Spades => 'S',
                Suit::Hearts => 'H',
                Suit::Diamonds => 'D',
                Suit::Clubs => 'C'
            }
        }
    }

    inverted_match_constructor! {
        pub fn from_serial(usize) -> Self { /* generated by inverted_match_constructor */ }
        pub fn to_serial(self) -> usize {
            match self {
                Suit::Spades => 0,
                Suit::Hearts => 1,
                Suit::Diamonds => 2,
                Suit::Clubs => 3
            }
        }
    }
}


impl std::fmt::Display for Suit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> Result<(), std::fmt::Error> {
        write!(f, "{}", self.to_char())
    }
}

